<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BasketbalFantasyApp.DAL\BasketbalFantasyApp.DAL.csproj" />
    <ProjectReference Include="..\BasketbalFantasyApp.Models\BasketbalFantasyApp.Models.csproj" />
  </ItemGroup>

</Project>
